INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10501', 'Wanda Maximoff', '30003', 'P39VN198', 'Nissan', '39500', 'Wheel Alignment', '1', '2', '1', '2', '123405678', 'Unpaid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10010', 'Virginia Potts', '30003', '39YVS415',	'Honda', '49900', 'Belt Replacement', '1', '2', '1', '2', '123450678', 'Unpaid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10062', 'Sam Wilson', '30003', '29T56WC3',	'Nissan', '51300', 'Tire Balancing', '1', '1', '1', '2', '123456780', 'Paid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10035', 'Happy Hogan', '30002', '9R2UHP54', 'Honda', '67900', 'Alternator Repair', '2', '4', '2', '6', '423186759', 'Paid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10053', 'Billy Batson', '30002', '5TR3K914',	'Nissan', '111000', 'Compressor Repair', '2', '1', '3', '6', '125689347', 'Paid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10010', 'Bruce Wayne', '30002', '15DC9A87',	'Toyota', '21000', 'B', '2', '6', '2', '8', '789123456', 'Paid');
INSERT INTO scheduled_services (C_ID, FULL_NAME, SC_ID, VIN, MANUFACTURER, MILEAGE, SCHEDULE_SERVICE, WEEK, DAY, START_TIME_SLOT, END_TIME_SLOT, MECHANIC_ID, INVOICE_STATUS) VALUES ('10001', 'Steve Rogers', '30002', '18S5R2D8',	'Nissan', '195500', 'A', '3', '5', '5', '8', '125689347', 'Paid');


INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('132457689','30001','MECHANIC','abcd1','abcd1')
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('314275869','30001','MECHANIC','abcd2','abcd2')
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('241368579','30001','MECHANIC','abcd3','abcd3')

INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('423186759','30002','MECHANIC','abcd4','abcd4');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123789456','30002','MECHANIC','abcd5','abcd5');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('789123456','30002','MECHANIC','abcd6','abcd6');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('125689347','30002','MECHANIC','abcd7','abcd7');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('347812569','30003','MECHANIC','abcd8','abcd8');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123456780','30003','MECHANIC','abcd9','abcd9');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123456708','30003','MECHANIC','abcd10','abcd10');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123456078','30003','MECHANIC','abcd11','abcd11');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123450678','30003','MECHANIC','abcd12','abcd12');
INSERT INTO EMPLOYEE_AUTH(EMP_ID,SC_ID,EMP_ROLE,USERNAME,PASSWORD) VALUES('123405678','30003','MECHANIC','abcd13','abcd13');

UPDATE CUSTOMER SET USERNAME = 'abc', PASSWORD = 'parker' WHERE C_NAME = 'Peter Parker';
UPDATE CUSTOMER SET USERNAME = 'def', PASSWORD = 'prince' WHERE C_NAME = 'Diana Prince';
UPDATE CUSTOMER SET USERNAME = 'ghi', PASSWORD = 'batson' WHERE C_NAME = 'Billy Batson';
UPDATE CUSTOMER SET USERNAME = 'jkl', PASSWORD = 'wayne' WHERE C_NAME = 'Bruce Wayne';
UPDATE CUSTOMER SET USERNAME = 'mno', PASSWORD = 'rogers' WHERE C_NAME = 'Steve Rogers';
UPDATE CUSTOMER SET USERNAME = 'pqr', PASSWORD = 'hogan' WHERE C_NAME = 'Happy Hogan';
UPDATE CUSTOMER SET USERNAME = 'stu', PASSWORD = 'stark' WHERE C_NAME = 'Tony Stark';
UPDATE CUSTOMER SET USERNAME = 'vwx', PASSWORD = 'romanoff' WHERE C_NAME = 'Natasha Romanoff';
UPDATE CUSTOMER SET USERNAME = 'xyz', PASSWORD = 'bullock' WHERE C_NAME = 'Harvey Bullock';
UPDATE CUSTOMER SET USERNAME = 'bcd', PASSWORD = 'wilson' WHERE C_NAME = 'Sam Wilson';
UPDATE CUSTOMER SET USERNAME = 'cde', PASSWORD = 'maximoff' WHERE C_NAME = 'Wanda Maximoff';
UPDATE CUSTOMER SET USERNAME = 'def', PASSWORD = 'potts' WHERE C_NAME = 'Virginia Potts';


Manager: :Add Employees
INSERT INTO EMPLOYEE (EMP_NAME, EMP_EMAIL, EMP_ADDRESS, EMP_CONTACT, EMP_ROLE, EMP_STARTDATE, EMP_COMPENSATION)VALUES(name, email_address, address, phone_number, role, start_date, compensation);

Manager: Setup Operational Hours
if yes:
INSERT INTO SERVICE_CENTER (WORKING_DAYS) VALUES ("Working on Saturday");

else
INSERT INTO SERVICE_CENTER (WORKING_DAYS) VALUES ("Not working on Saturday");

Manager: Setup Repair Service Prices
UPDATE SERVICES_PROVIDED_DETAILS
SET price = belt_replacement_price
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Belt Replacement');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = engine_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Engine Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = catalytic_converter_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Catalytic Converter Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = muffler_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Muffler Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = power_lock_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Power Lock Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = axle_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Axle Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = transmission_flush_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Transmission Flush Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = tire_balancing_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Tire Balancing Repair');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = wheel_alignment_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Wheel Alignment');
UPDATE SERVICES_PROVIDED_DETAILS
SET price = compressor_repair_price 
WHERE s_no = (SELECT DISTINCT s_no
		FROM SERVICES
		WHERE s_name = 'Compressor Repair');

Manager: Setup Maintenance Service Prices
UPDATE MAINTENANCE_PRICES
SET price = schedule_a_price 
WHERE schedule_name= 'A';

UPDATE MAINTENANCE_PRICES
SET price = schedule_b_price 
WHERE schedule_name= 'B';

UPDATE MAINTENANCE_PRICES
SET price = schedule_c_price 
WHERE schedule_name= 'C';

Manager: Add New Employees
INSERT INTO EMPLOYEE (EMP_NAME, EMP_EMAIL, EMP_ADDRESS, EMP_CONTACT, EMP_ROLE, EMP_STARTDATE, EMP_COMPENSATION)VALUES(name, email_address, address, phone_number, role, start_date, compensation);